- platform: aht10
  temperature:
    name: "Temperatur"
    icon: mdi:thermometer-high
  humidity:
    name: "Relative Luftfeuchtigkeit"
    icon: mdi:water-percent
    accuracy_decimals: 1
  update_interval: 60s
  address: 0x38
  