- platform: bme680_bsec
  bme680_bsec_id: bme680_internal
  temperature:
    name: "Temperatur"
    #oversampling: 16x
    icon: mdi:thermometer-high
  pressure:
    name: "Luftdruck"
    icon: mdi:gauge
  humidity:
    id: "humidity"
    name: "Relative Luftfeuchtigkeit"
    icon: mdi:water-percent
  co2_equivalent:
    name: "BME680 CO2 Equivalent"
    icon: mdi:molecule-co2
  breath_voc_equivalent:
    name: "BME680 Breath VOC Equivalent"
  #gas_resistance:
    #id: "gas_resistance"
    #name: "Gas Widerstand"
    #icon: mdi:molecule-co2
  #address: 0x77
  #update_interval: 60s
#- platform: template
  #name: "Luftqualit√§t"
  #id: iaq
  #icon: "mdi:gauge"
  # caulculation: comp_gas = log(R_gas[ohm]) + 0.04 log(Ohm)/%rh * hum[%rh]
  #lambda: |-
    #return log(id(gas_resistance).state) + 0.04 *  id(humidity).state;
