- platform: hlw8012
  sel_pin: 5
  cf_pin: 14
  cf1_pin: 13
  update_interval: 2s
  id: power
  
  current:
    name: "Aktuell - Ampere"
    unit_of_measurement: A
    accuracy_decimals: 3
    icon: mdi:current-ac

  voltage:
    name: "Aktuell - Volt"
    unit_of_measurement: V
    accuracy_decimals: 1
    icon: mdi:flash-outline

  power:
    name: "Aktuell - Watt"
    unit_of_measurement: W
    id: "power_wattage"
    icon: mdi:gauge