name: ${devicename}
friendly_name: ${friendly_devicename}
comment: "${comment}"
name_add_mac_suffix: false
project:
  name: "${project_name}"
  version: "${project_version}"
# OTA password change
#on_boot:
  #- lambda: |-
      #id(ota_pw).set_auth_password("new-ota-password");
