- platform: ssd1306_i2c
  model: SSD1306_128X32
  address: 0x3C
  setup_priority: -200.0
  id: my_display
  lambda: !lambda |-
    if (id(bad_occupancy).state) {
      ESP_LOGD("custom", "Sensor hat einen Status");
      it.print(4, 0, id(mdi_font_24), "\U000F1158");
      it.printf(30, 0, id(roboto_22), "%s", "Besetzt");
    } else {
      ESP_LOGD("custom", "Kein Status");
      it.print(4, 0, id(mdi_font_24), "\U000F1158");
      it.printf(30, 0, id(roboto_22), "%s", "Frei");
    }