wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # domain: !secret domain
  fast_connect: true
  min_auth_mode: WPA2
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Setup ${friendly_devicename}"
    password: !secret fallback_hotspot_password
    #manual_ip:
      #static_ip: !secret fallback_hotspot_static_ip
      #gateway: !secret fallback_hotspot_gateway
      #subnet: !secret fallback_hotspot_subnet
