# Base settings
<<: !include ../common/device_base.yaml

# Web Server
<<: !include ../common/generic/web_server.yaml

# Captive Portal
<<: !include ../common/generic/captive_portal.yaml

# Board selection
<<: !include ../boards/esp8266-esp8285.yaml

# Button configuration
binary_sensor:
  - platform: gpio
    id: pushbutton
    internal: true
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle: relay1

# Config for switches
switch:
  - platform: gpio
    pin: GPIO14
    id: relay2
    name: "Sockel 2"
  - platform: gpio
    pin: GPIO5
    id: relay3
    name: "Sockel 3"
  - platform: gpio
    pin: GPIO15
    id: relay4
    name: "USB-Ports"

# Relay1 is set up as a light
output:
  - platform: gpio
    id: light_relay
    pin: GPIO12

# Relay1 is set up as a light
light:
  - platform: binary
    id: relay1
    name: "Floorlamp"
    output: light_relay

# Status LED for connection
status_led:
  pin:
    number: GPIO0