# Base settings
<<: !include ../common/device_base.yaml

# Web Server
<<: !include ../common/generic/web_server.yaml

# Captive Portal
<<: !include ../common/generic/captive_portal.yaml

# Board selection
<<: !include ../boards/esp8266-esp8285.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: ${friendly_devicename}
    id: relay
    icon: mdi:power
    pin: GPIO12

status_led:
  pin:
    number: GPIO13
    inverted: yes