# Base settings
<<: !include ../common/device_base.yaml

# Web Server
<<: !include ../common/generic/web_server.yaml

# Captive Portal
<<: !include ../common/generic/captive_portal.yaml

# Board selection
<<: !include ../boards/esp8266-esp8285.yaml


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${devicename}_button_state"
    on_press:
      - switch.toggle: fakebutton

  - platform: template
    name: SonOff POW Running
    filters:
      - delayed_off: 15s
    lambda: |-
      if (isnan(id(power).state)) {
          return {};
      } else if (id(power).state > 4) {
          // Running
          return true;
      } else {
          // Not running
          return false;
      }

sensor:
  <<: !include ../common/sensor/hlw8012.yaml

switch:
  - platform: template
    name: Switch
    optimistic: true
    id: fakebutton
    icon: mdi:power
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO15
      inverted: true

light:
  - platform: monochromatic
    name: LED
    output: pow_blue_led
    id: led