substitutions:
  devicename: "athompresence01"
  friendly_devicename: "Pr√§senz Bad"
  room: "Badezimmer"
  comment: "Athom Presence Sensor Bad"
  project_name: "Athom.Presence Sensor"
  project_version: "1.0"

<<: !include devicetypes/athom-presence.yaml
