substitutions:
  devicename: "athompresence03"
  friendly_devicename: "Pr채senz K체che"
  room: "K체che"
  comment: "Athom Presence Sensor K체che"
  project_name: "Athom.Presence Sensor"
  project_version: "1.0"

<<: !include devicetypes/athom-presence.yaml
