substitutions:
  devicename: "esp32-04"
  friendly_devicename: "ESP32 04"
  room: "Auf Lager"
  comment: "ESP32 04"
  project_name: "Espressif.ESP32"
  project_version: "1.0"

<<: !include devicetypes/esp32.yaml
