substitutions:
  devicename: "esp8266-03"
  friendly_devicename: "Display Bad"
  room: "Badezimmer"
  comment: "Bad TÃ¼r-Display"
  project_name: "Wemos.D1 Mini ESP8266"
  project_version: "2.0"

<<: !include devicetypes/esp8266-d1-mini_v2.yaml

i2c:
  sda: D1
  scl: D2
  # OLED displays
  frequency: 400kHz
  scan: false

# OLED displays
font:
  - file: "common/fonts/materialdesignicons-webfont.ttf"  # Material Design Icons font
    id: mdi_font_24
    size: 24  # Adjust the size as needed
    glyphs:
      - "\U000F1158" # mdi:paper-roll-outline
      - "\U000F09A1" # mdi:shower-head

  - file: "gfonts://Roboto"
    id: roboto_24
    size: 24

  - file: "gfonts://Roboto"
    id: roboto_22
    size: 22
  #<<: !include common/fonts/font.yaml

<<: !include devicetypes/esp8266-d1-mini.yaml

esphome:
  <<: !include common/section-esphome.yaml

# OLED displays
display:
  # OLED display 128 x 32 pixel
  <<: !include common/display/ssd1306_128x32.yaml

<<: !include common/section-system.yaml

binary_sensor:
  - <<: !include common/binary_sensor/status.yaml
  - platform: homeassistant
    id: bad_occupancy
    # entity_id: binary_sensor.firetab_eg_eingesteckt_2
    entity_id: binary_sensor.presence_bad_occupancy
    # entity_id: binary_sensor.prasenz_keller_occupancy
    internal: true
sensor:
  - <<: !include common/sensor/uptime.yaml
  - <<: !include common/sensor/wifi_signal.yaml

text_sensor:
  - <<: !include common/text_sensor/version.yaml

button:
  - <<: !include common/button/restart.yaml