
substitutions:
  devicename: "esp8266-05"
  friendly_devicename: "esp8266-05"
  room: "Auf Lager"
  comment: "ESP8266-05"
  project_name: "Wemos.D1 Mini ESP8266"
  project_version: "1.0"

<<: !include devicetypes/esp8266-d1-mini_v2.yaml

esphome:
  <<: !include common/section-esphome.yaml

<<: !include common/section-system.yaml

text_sensor:
  - <<: !include common/text_sensor/version.yaml
  - <<: !include common/text_sensor/wifi_info.yaml

