substitutions:
  devicename: "gosundplug09"
  friendly_devicename: "Kühlschrank"
  room: "Küche"
  comment: "Gosund SP111 Kühlschrank"
  project_name: "Gosund.SP111"
  project_version: "1.0"

  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"

<<: !include devicetypes/gosund-sp111-always-on.yaml
