substitutions:
  devicename: "rpi-pico-03"
  friendly_devicename: "Raspberry Pi Pico W 03"
  room: "Auf Lager"
  comment: "Raspberry Pi Pico W 03"
  project_name: "Raspberry Pi.Pico W"
  project_version: "1.0"

<<: !include devicetypes/raspberrypi-pico-w.yaml