substitutions:
  devicename: "sonoffbasicr2-01"
  friendly_devicename: "Licht Werkstatt Wand"
  room: "Werkstatt"
  comment: "Licht Werkstatt Wand"
  project_name: "Sonoff.Basic R2"
  project_version: "1.0"

<<: !include devicetypes/sonoff-basic-r2.yaml
