substitutions:
  devicename: "sonoffpowr2-02"
  friendly_devicename: "Waschmaschine"
  room: "Keller"
  comment: "Sonoff POW R2 Waschmaschine"
  project_name: "Sonoff.POW R2"
  project_version: "1.0"

<<: !include devicetypes/sonoff-pow-r2.yaml
