

#- file: common/fonts/${font_name}.ttf
  #id: ${font_name}
  #size: ${font_size}

#- file: 'common/fonts/MaterialIcons-Regular.ttf'
  #id: mdi_font_48
  #size: 48
  #glyphs: [
    #'󱅘', # mdi:paper-roll-outline
    #'󰦡' # mdi:shower-head
  #]
